### ISSUE TITLE
Minimum PHP version difference from phpro/grumphp

### ISSUE THREAD

**Issue by TravisCarden** [phpro/grumphp-shim#18]
Hi! Can PHP 7 support be restored to this shim the same way it was restored to the main package with the v1.11.0 release? I maintain a library that, sadly, still has to support 7.4. Thanks.

**Comment by veewee** [comment]
Nice catch.
It should be possible if the build tools support up until 7.4 and those directly embedded dependencies support from 7.4 up to 8.1. 

Will have to play around with it to see if it's possible.

**Comment by veewee** [comment]
Latest release is compiled with PHP 7.4 as minimum PHP target.
Thanks for reporting.
