### ISSUE TITLE
"grumphp" shell-script broken

### ISSUE THREAD

**Issue by prilka** [phpro/grumphp-shim#3]
With the changes in #2 (c59799482d767535a85a7340ed6b040ff4d9c15b) it's no longer possible to call the shell-script if the current working directory is not `vendor/bin`

Command:
```
vendor/bin/grumphp
```

Error:

```
PHP Warning:  require(phar://grumphp.phar/.box/bin/check-requirements.php): failed to open stream: phar error: invalid url or non-existent phar "phar://grumphp.phar/.box/bin/check-requirements.php" in /path/to/my/project/vendor/phpro/grumphp-shim/grumphp on line 9
```

**Comment by stijnbernards** [comment]
The same is happening for me.

It seems that the following commit broke the grumphp executable: https://github.com/phpro/grumphp-shim/commit/c59799482d767535a85a7340ed6b040ff4d9c15b
